#! /bin/csh -f

# source vpi3.setup first

gcc  -c -O3 src/vpi3_72.c src/qq64.c \
     -Wall \
     -I$PYTHONINC1  \
     -I$PYTHONINC2  \
     -Isrc \
     -fPIC \

ld   -shared --export-dynamic   -o vpi7.so \
    vpi3_72.o qq64.o \
    -L/usr/lib \
    -L$PYTHONLIB \
    -lpython$PYTHONVERSION \
    -lc  -lpthread -lutil \


