#! /bin/csh -f


# set INC = /home/iliag/local/include/python3.8 
# set INC1 = /tools/common/pkgs/python/current/include/python3.6m
# set INC2 = /tools/cdnc/XCELIUM/current/tools/include/




set LIB = /tools/common/pkgs/python/current/lib
set INC1 = /home/iliag/local/include/python3.8 
set LIB = /home/iliag/local/lib
set MTI_HOME = /tools/cdnc/XCELIUM/current/tools.lnx86/include/
gcc  -c -O3 src/vpi3_local.c src/qq64.c \
     -Wall \
     -I$INC1 \
     -I$MTI_HOME \
     -fPIC \



ld -shared  -export-dynamic  \
    -o vpi7.so \
    vpi3_local.o qq64.o \
    -L/usr/lib \
    -L$LIB \
    -lpython3.8 \
    -lc  -lpthread -lutil \



