#! /bin/csh -f


set MTI_HOME = /home/ilia/software/gplcver-2.12a.src/pli_incs
set INC = /Users/ilia/local/include/python3.6m 
gcc  -c -g -I$MTI_HOME src/vpi3_72.c src/qq64.c \
     -Wall \
     -I$INC \
     -Isrc \
     -fPIC \

ld   -dylib  -o vpi7_nc_36.so \
    vpi3_72.o qq64.o \
    -L/usr/lib \
    -L/Users/ilia/local/lib \
    -lpython3.6m \
    -lc  -lpthread -lutil \
    -macosx_version_min 10.11 \



