#! /bin/csh -f

set INC = /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/
set LIB = /Library/Frameworks/Python.framework/Versions/3.8/lib



set MTI_HOME = /home/ilia/software/gplcver-2.12a.src/pli_incs
set INC = /Users/ilia/local/include/python3.6m 
gcc  -c -O3 src/vpi3_72.c src/qq64.c \
     -Wall \
     -I$INC \
     -Isrc \
     -fPIC \

ld   -shared --export-dynamic   -o vpi7.so \
    vpi3.o qq64.o \
    -L/usr/lib \
    -L$LIB \
    -lpython3.8 \
    -lc  -lpthread -lutil \



