#! /bin/csh -f

set INC = /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/
set LIB = /Library/Frameworks/Python.framework/Versions/3.10/lib

iverilog-vpi src/vpi3_72.c src/qq64.c \
    -I$INC \
    -lpython3.10  \
    -L$LIB \




#    -lpython3.6m  \
#    -L/Users/ilia/local/lib/ \






