#! /bin/csh -f

# source first vpi3.setup (your version of that file!)


# echo $PYTHONLIB
# echo $PYTHONHOME


iverilog-vpi src/vpi3_72.c src/qq64.c \
    -I$PYTHONINC1 \
    -lpython$PYTHONVERSION  \
    -L$PYTHONLIB \










