#! /bin/csh -f

# prepare files.list of all verilog files involved.
# dont forget to source my_vpi3.setup

iverilog -g2012 -o tb.vvp -f files.list 

vvp   -M$VPI3 -mvpi3_local -lver.log tb.vvp +SEQ=$1 $2 $3

