#! /bin/csh -f
# setenv PYTHONHOME "/Library/Frameworks/Python.framework/Versions/3.9/lib:/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages:/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/"
# setenv PYTHONPATH /Library/Frameworks/Python.framework/Versions/3.9/bin
comp
simv +SEQ=test.seq




