#! /bin/csh -f

vcs -sverilog -debug -f files.list  +define+UNIT_DELAY \
    -timescale=1ns/1ps -l comp.log +lint=TFIPC-L \
   -full64 +v2k +vpi -load /home/iliag/software/vpi/vpi7_nc_27.so:vpit_RegisterTfs  \
   +libext+.v+ \
   -notice \
   +vcs+vcdpluson \
    +error+1000




