
import logs
import veri
def monitorStuff(Net):
    Val = logs.peek(Net)
    if Val!=0:
        logs.log_error('PANIC activated on %s %s'%(Net,veri.peek(Net)))
        return 1
    return 0


def monitorStuffs():
    panics=0
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.a_rcount")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.b_rcount")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.c_rcount")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.d_rcount")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.a_ids_fifo.next_count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.a_ids_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.b_ids_fifo.next_count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.b_ids_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.c_ids_fifo.next_count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.c_ids_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.d_ids_fifo.next_count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.d_ids_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.rdata_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_rd_4_merger.rdata_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_acount")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_bcount")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_ccount")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_dcount")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_bcount")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_pri_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_bcount")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_pri_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_bcount")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_pri_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_bcount")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_pri_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_b_fifo.next_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_b_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_win_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_win_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_b_fifo.next_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_b_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_out_fifo.next_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_out_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_win_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_win_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_b_fifo.next_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_b_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_win_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_win_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.int_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_b_fifo.next_count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_b_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_win_fifo.count")
    counts += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_win_fifo.int_count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.int_count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.ar_fifo.next_count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.ar_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.int_count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.int_count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.int_count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.r_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.r_fifo.int_count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.a_bcount")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.b_bcount")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.c_bcount")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.d_bcount")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.aw_fifo.next_count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.aw_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.b_fifo.next_count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.b_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.int_count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.int_count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.int_count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.int_count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.order_fifo.next_count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.order_fifo.count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.w_fifo.next_count")
    counts += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.w_fifo.count")

    veri.force('tb.Panics',str(panics))
def snapshot():
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.a_rcount" % logs.peek("tb.dut.merger0.axi_rd_4_merger.a_rcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.b_rcount" % logs.peek("tb.dut.merger0.axi_rd_4_merger.b_rcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.c_rcount" % logs.peek("tb.dut.merger0.axi_rd_4_merger.c_rcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.d_rcount" % logs.peek("tb.dut.merger0.axi_rd_4_merger.d_rcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.int_count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.a_ids_fifo.next_count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.a_ids_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.a_ids_fifo.count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.a_ids_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.int_count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.b_ids_fifo.next_count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.b_ids_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.b_ids_fifo.count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.b_ids_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.int_count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.c_ids_fifo.next_count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.c_ids_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.c_ids_fifo.count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.c_ids_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.int_count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.d_ids_fifo.next_count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.d_ids_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.d_ids_fifo.count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.d_ids_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.rdata_fifo.count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.rdata_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.rdata_fifo.int_count" % logs.peek("tb.dut.merger0.axi_rd_4_merger.rdata_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_acount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_acount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_bcount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_bcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_ccount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_ccount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_dcount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_dcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_bcount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_bcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_pri_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_pri_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_bcount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_bcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_pri_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_pri_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_bcount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_bcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_pri_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_pri_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_bcount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_bcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_pri_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_pri_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.int_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_b_fifo.next_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_b_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_b_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_b_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_win_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_win_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_win_fifo.int_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_win_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.int_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_b_fifo.next_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_b_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_b_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_b_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_out_fifo.next_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_out_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_out_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_out_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_win_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_win_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_win_fifo.int_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_win_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.int_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_b_fifo.next_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_b_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_b_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_b_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_win_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_win_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_win_fifo.int_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_win_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.int_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_b_fifo.next_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_b_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_b_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_b_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_win_fifo.count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_win_fifo.count"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_win_fifo.int_count" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_win_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.int_count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.ar_fifo.next_count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.ar_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.ar_fifo.count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.ar_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.int_count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.int_count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.int_count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.r_fifo.count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.r_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.r_fifo.int_count" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.r_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.a_bcount" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.a_bcount"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.b_bcount" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.b_bcount"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.c_bcount" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.c_bcount"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.d_bcount" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.d_bcount"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.aw_fifo.next_count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.aw_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.aw_fifo.count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.aw_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.b_fifo.next_count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.b_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.b_fifo.count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.b_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.int_count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.int_count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.int_count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.int_count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.int_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.order_fifo.next_count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.order_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.order_fifo.count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.order_fifo.count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.w_fifo.next_count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.w_fifo.next_count"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.w_fifo.count" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.w_fifo.count"))
