#! /bin/csh -f

llbin/table2c.py verilog_tables
/bin/cp tables.c src/verilog_tables.c

set FLAGS = '-O3'
set FLAGS = '-g'
gcc src/verilog_tables.c src/nlexer.c -o verilog_lexer $FLAGS

/bin/cp verilog_lexer  ../pybin/

# optional. not required
/bin/cp verilog_lexer  ~/bin/


