#! /bin/csh -f

llbin/table2c.py verilog_tables
# /bin/cp tables.c src/verilog_tables.c

set FLAGS = '-O3'
set FLAGS = '-g'
gcc src/verilog_tables.c src/nlexer.c -o ../pybin3/verilog_lexer $FLAGS

# optional. not required
gcc src/verilog_tables.c src/nlexer.c -o ~/bin/verilog_lexer $FLAGS


