#! /bin/csh -f



gcc src/vcd_records.c -o vcd_records -O3
gcc src/vcd_trim.c -o vcd_trim -O3
gcc src/vcd_cut_time.c -o vcd_cut_time -O3



/bin/cp vcd_records ~/bin/
/bin/cp vcd_trim ~/bin/
/bin/cp vcd_cut_time ~/bin/


