#! /bin/csh -f

set VERSION = 10
# this is how i compile on my macbook Pro. for Python3

gcc -g src3/vcd_python.c  src3/qq64.c  -o vcd_python3 \
  -I/Library/Frameworks/Python.framework/Versions/3.$VERSION/include/python3.$VERSION/ \
  -lpython3.$VERSION -L/Library/Frameworks/Python.framework/Versions/3.$VERSION/lib \

gcc -g src3/vcd_python.c  src3/qq64.c  -o ~/bin/vcd_python3 \
  -I/Library/Frameworks/Python.framework/Versions/3.$VERSION/include/python3.$VERSION/ \
  -lpython3.$VERSION -L/Library/Frameworks/Python.framework/Versions/3.$VERSION/lib \


