#! /bin/csh -f

# this is how i compile on my macbook Pro. for Python3

gcc -g src3/vcd_python2.c  src3/qq64.c  -o vcd_python32 \
  -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/ \
  -lpython3.9 -L/Library/Frameworks/Python.framework/Versions/3.9/lib \



