#! /bin/csh -f
set VERSION = 10
# this is how i compile on my macbook Pro. for Python3
set ME = `whoami`
gcc -g src3/vcd_python2.c  src3/qq64.c  -o vcd_python32 \
  -I/Library/Frameworks/Python.framework/Versions/3.$VERSION/include/python3.$VERSION/ \
  -lpython3.$VERSION -L/Library/Frameworks/Python.framework/Versions/3.$VERSION/lib \


gcc -g src3/vcd_python2.c  src3/qq64.c  -o /Users/$ME/bin/vcd_python32 \
  -I/Library/Frameworks/Python.framework/Versions/3.$VERSION/include/python3.$VERSION/ \
  -lpython3.$VERSION -L/Library/Frameworks/Python.framework/Versions/3.$VERSION/lib \

