#! /bin/csh -f

# yum install zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel
tar xzf  Python-3.10.2.tar.gz
cd Python-3.10.2/
./configure --prefix  $HOME --exec_prefix $HOME --enable-shared

make
make install





