#! /bin/csh -f

../llbin/makeNoc.py x16.dot

iverilog -o tb.vvp  -g2012  \
    x16_tb.v \
    x16_noc.v \
    ../rtl/axi_4_merger.v \
    ../rtl/axi_4_splitter.v \
    ../rtl/axi_wr_4_merger.v \
    ../rtl/axi_wr_4_splitter.v \
    ../rtl/axi_rd_4_merger.v \
    ../rtl/axi_rd_4_splitter.v \
    ../rtl/syncfifo.v \
    ../rtl/syncfifo_sampled.v \
    ../rtl/axi2ram.v \



