#! /bin/csh -f

# change the paths below to your system

iverilog-vpi src/vpi7.c src/qq64.c \
    -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/ \
    -lpython2.7 -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib \







