
import logs
import veri
def monitorStuff(Net):
    Val = logs.peek(Net)
    if Val!=0:
        logs.log_error('PANIC activated on %s %s'%(Net,veri.peek(Net)))
        return 1
    return 0


def monitorStuffs():
    panics=0
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.panic_d_ids_fifo")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.panic_c_ids_fifo")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.panic_b_ids_fifo")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.panic_a_ids_fifo")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.rdata_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_rd_4_merger.rdata_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_acount")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_bcount")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_ccount")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_dcount")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_rw_fifo")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_d_aw_fifo")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_c_aw_fifo")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_b_out_fifo")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_b_aw_fifo")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_aw_fifo")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.panic_a_aw_fifo")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.a_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.b_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.c_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.d_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.rw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger0.axi_wr_4_merger.rw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.panic_d_ids_fifo")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.panic_c_ids_fifo")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.panic_b_ids_fifo")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.panic_a_ids_fifo")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.a_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.a_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.b_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.b_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.c_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.c_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.d_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.d_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.rdata_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_rd_4_merger.rdata_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.panic_acount")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.panic_bcount")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.panic_ccount")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.panic_dcount")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.panic_rw_fifo")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.panic_d_aw_fifo")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.panic_c_aw_fifo")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.panic_b_out_fifo")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.panic_b_aw_fifo")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.panic_aw_fifo")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.panic_a_aw_fifo")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.a_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.a_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.a_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.a_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.b_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.b_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.b_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.b_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.c_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.c_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.c_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.c_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.d_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.d_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.d_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.d_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.rw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger1.axi_wr_4_merger.rw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.panic_d_ids_fifo")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.panic_c_ids_fifo")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.panic_b_ids_fifo")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.panic_a_ids_fifo")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.a_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.a_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.b_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.b_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.c_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.c_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.d_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.d_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.rdata_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_rd_4_merger.rdata_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.panic_acount")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.panic_bcount")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.panic_ccount")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.panic_dcount")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.panic_rw_fifo")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.panic_d_aw_fifo")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.panic_c_aw_fifo")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.panic_b_out_fifo")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.panic_b_aw_fifo")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.panic_aw_fifo")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.panic_a_aw_fifo")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.a_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.a_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.a_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.a_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.b_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.b_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.b_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.b_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.c_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.c_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.c_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.c_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.d_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.d_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.d_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.d_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.rw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger2.axi_wr_4_merger.rw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.panic_d_ids_fifo")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.panic_c_ids_fifo")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.panic_b_ids_fifo")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.panic_a_ids_fifo")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.a_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.a_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.b_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.b_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.c_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.c_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.d_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.d_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.rdata_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_rd_4_merger.rdata_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.panic_acount")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.panic_bcount")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.panic_ccount")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.panic_dcount")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.panic_rw_fifo")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.panic_d_aw_fifo")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.panic_c_aw_fifo")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.panic_b_out_fifo")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.panic_b_aw_fifo")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.panic_aw_fifo")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.panic_a_aw_fifo")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.a_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.a_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.a_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.a_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.b_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.b_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.b_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.b_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.c_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.c_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.c_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.c_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.d_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.d_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.d_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.d_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.rw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger3.axi_wr_4_merger.rw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.panic_d_ids_fifo")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.panic_c_ids_fifo")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.panic_b_ids_fifo")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.panic_a_ids_fifo")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.a_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.a_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.b_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.b_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.c_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.c_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.d_ar_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.d_ar_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.rdata_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_rd_4_merger.rdata_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.panic_acount")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.panic_bcount")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.panic_ccount")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.panic_dcount")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.panic_rw_fifo")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.panic_d_aw_fifo")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.panic_c_aw_fifo")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.panic_b_out_fifo")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.panic_b_aw_fifo")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.panic_aw_fifo")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.panic_a_aw_fifo")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.a_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.a_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.a_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.a_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.b_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.b_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.b_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.b_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.c_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.c_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.c_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.c_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.d_aw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.d_aw_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.d_win_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.d_win_fifo.panic_out")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.rw_fifo.panic_in")
    panics += monitorStuff("tb.dut.merger4.axi_wr_4_merger.rw_fifo.panic_out")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.panic_r_fifo")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.panic_ar_fifo")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.panic_in")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.panic_out")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.panic_in")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.panic_out")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.back_r_fifo.panic_in")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.back_r_fifo.panic_out")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.panic_in")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.panic_out")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.panic_in")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.panic_out")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.r_fifo.panic_in")
    panics += monitorStuff("tb.dut.splitter0.axi_rd_4_splitter.r_fifo.panic_out")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.panic_w_fifo")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.panic_order_fifo")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.panic_b_fifo")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.panic_aw_fifo")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.panic_in")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.panic_out")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.panic_in")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.panic_out")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.panic_in")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.panic_out")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.panic_in")
    panics += monitorStuff("tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.panic_out")

    veri.force('tb.Panics',str(panics))
def snapshot():
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.panic_d_ids_fifo" % logs.peek("tb.dut.merger0.axi_rd_4_merger.panic_d_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.panic_c_ids_fifo" % logs.peek("tb.dut.merger0.axi_rd_4_merger.panic_c_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.panic_b_ids_fifo" % logs.peek("tb.dut.merger0.axi_rd_4_merger.panic_b_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.panic_a_ids_fifo" % logs.peek("tb.dut.merger0.axi_rd_4_merger.panic_a_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_rd_4_merger.a_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_rd_4_merger.b_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_rd_4_merger.c_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_rd_4_merger.d_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.rdata_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_rd_4_merger.rdata_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_rd_4_merger.rdata_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_rd_4_merger.rdata_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_acount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_acount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_bcount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_bcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_ccount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_ccount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_dcount" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_dcount"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_rw_fifo" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_rw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_d_aw_fifo" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_d_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_c_aw_fifo" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_c_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_b_out_fifo" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_b_out_fifo"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_b_aw_fifo" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_b_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_aw_fifo" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.panic_a_aw_fifo" % logs.peek("tb.dut.merger0.axi_wr_4_merger.panic_a_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_win_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.a_win_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_wr_4_merger.a_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.aw_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_wr_4_merger.aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.aw_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_wr_4_merger.aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_win_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.b_win_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_wr_4_merger.b_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_win_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.c_win_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_wr_4_merger.c_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_win_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.d_win_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_wr_4_merger.d_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.rw_fifo.panic_in" % logs.peek("tb.dut.merger0.axi_wr_4_merger.rw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger0.axi_wr_4_merger.rw_fifo.panic_out" % logs.peek("tb.dut.merger0.axi_wr_4_merger.rw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.panic_d_ids_fifo" % logs.peek("tb.dut.merger1.axi_rd_4_merger.panic_d_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.panic_c_ids_fifo" % logs.peek("tb.dut.merger1.axi_rd_4_merger.panic_c_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.panic_b_ids_fifo" % logs.peek("tb.dut.merger1.axi_rd_4_merger.panic_b_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.panic_a_ids_fifo" % logs.peek("tb.dut.merger1.axi_rd_4_merger.panic_a_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.a_ar_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_rd_4_merger.a_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.a_ar_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_rd_4_merger.a_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.b_ar_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_rd_4_merger.b_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.b_ar_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_rd_4_merger.b_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.c_ar_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_rd_4_merger.c_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.c_ar_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_rd_4_merger.c_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.d_ar_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_rd_4_merger.d_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.d_ar_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_rd_4_merger.d_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.rdata_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_rd_4_merger.rdata_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_rd_4_merger.rdata_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_rd_4_merger.rdata_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.panic_acount" % logs.peek("tb.dut.merger1.axi_wr_4_merger.panic_acount"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.panic_bcount" % logs.peek("tb.dut.merger1.axi_wr_4_merger.panic_bcount"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.panic_ccount" % logs.peek("tb.dut.merger1.axi_wr_4_merger.panic_ccount"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.panic_dcount" % logs.peek("tb.dut.merger1.axi_wr_4_merger.panic_dcount"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.panic_rw_fifo" % logs.peek("tb.dut.merger1.axi_wr_4_merger.panic_rw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.panic_d_aw_fifo" % logs.peek("tb.dut.merger1.axi_wr_4_merger.panic_d_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.panic_c_aw_fifo" % logs.peek("tb.dut.merger1.axi_wr_4_merger.panic_c_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.panic_b_out_fifo" % logs.peek("tb.dut.merger1.axi_wr_4_merger.panic_b_out_fifo"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.panic_b_aw_fifo" % logs.peek("tb.dut.merger1.axi_wr_4_merger.panic_b_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.panic_aw_fifo" % logs.peek("tb.dut.merger1.axi_wr_4_merger.panic_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.panic_a_aw_fifo" % logs.peek("tb.dut.merger1.axi_wr_4_merger.panic_a_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.a_aw_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_wr_4_merger.a_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.a_aw_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_wr_4_merger.a_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.a_win_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_wr_4_merger.a_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.a_win_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_wr_4_merger.a_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.aw_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_wr_4_merger.aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.aw_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_wr_4_merger.aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.b_aw_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_wr_4_merger.b_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.b_aw_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_wr_4_merger.b_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.b_win_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_wr_4_merger.b_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.b_win_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_wr_4_merger.b_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.c_aw_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_wr_4_merger.c_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.c_aw_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_wr_4_merger.c_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.c_win_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_wr_4_merger.c_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.c_win_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_wr_4_merger.c_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.d_aw_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_wr_4_merger.d_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.d_aw_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_wr_4_merger.d_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.d_win_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_wr_4_merger.d_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.d_win_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_wr_4_merger.d_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.rw_fifo.panic_in" % logs.peek("tb.dut.merger1.axi_wr_4_merger.rw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger1.axi_wr_4_merger.rw_fifo.panic_out" % logs.peek("tb.dut.merger1.axi_wr_4_merger.rw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.panic_d_ids_fifo" % logs.peek("tb.dut.merger2.axi_rd_4_merger.panic_d_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.panic_c_ids_fifo" % logs.peek("tb.dut.merger2.axi_rd_4_merger.panic_c_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.panic_b_ids_fifo" % logs.peek("tb.dut.merger2.axi_rd_4_merger.panic_b_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.panic_a_ids_fifo" % logs.peek("tb.dut.merger2.axi_rd_4_merger.panic_a_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.a_ar_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_rd_4_merger.a_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.a_ar_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_rd_4_merger.a_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.b_ar_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_rd_4_merger.b_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.b_ar_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_rd_4_merger.b_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.c_ar_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_rd_4_merger.c_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.c_ar_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_rd_4_merger.c_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.d_ar_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_rd_4_merger.d_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.d_ar_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_rd_4_merger.d_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.rdata_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_rd_4_merger.rdata_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_rd_4_merger.rdata_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_rd_4_merger.rdata_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.panic_acount" % logs.peek("tb.dut.merger2.axi_wr_4_merger.panic_acount"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.panic_bcount" % logs.peek("tb.dut.merger2.axi_wr_4_merger.panic_bcount"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.panic_ccount" % logs.peek("tb.dut.merger2.axi_wr_4_merger.panic_ccount"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.panic_dcount" % logs.peek("tb.dut.merger2.axi_wr_4_merger.panic_dcount"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.panic_rw_fifo" % logs.peek("tb.dut.merger2.axi_wr_4_merger.panic_rw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.panic_d_aw_fifo" % logs.peek("tb.dut.merger2.axi_wr_4_merger.panic_d_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.panic_c_aw_fifo" % logs.peek("tb.dut.merger2.axi_wr_4_merger.panic_c_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.panic_b_out_fifo" % logs.peek("tb.dut.merger2.axi_wr_4_merger.panic_b_out_fifo"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.panic_b_aw_fifo" % logs.peek("tb.dut.merger2.axi_wr_4_merger.panic_b_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.panic_aw_fifo" % logs.peek("tb.dut.merger2.axi_wr_4_merger.panic_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.panic_a_aw_fifo" % logs.peek("tb.dut.merger2.axi_wr_4_merger.panic_a_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.a_aw_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_wr_4_merger.a_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.a_aw_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_wr_4_merger.a_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.a_win_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_wr_4_merger.a_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.a_win_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_wr_4_merger.a_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.aw_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_wr_4_merger.aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.aw_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_wr_4_merger.aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.b_aw_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_wr_4_merger.b_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.b_aw_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_wr_4_merger.b_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.b_win_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_wr_4_merger.b_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.b_win_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_wr_4_merger.b_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.c_aw_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_wr_4_merger.c_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.c_aw_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_wr_4_merger.c_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.c_win_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_wr_4_merger.c_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.c_win_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_wr_4_merger.c_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.d_aw_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_wr_4_merger.d_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.d_aw_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_wr_4_merger.d_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.d_win_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_wr_4_merger.d_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.d_win_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_wr_4_merger.d_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.rw_fifo.panic_in" % logs.peek("tb.dut.merger2.axi_wr_4_merger.rw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger2.axi_wr_4_merger.rw_fifo.panic_out" % logs.peek("tb.dut.merger2.axi_wr_4_merger.rw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.panic_d_ids_fifo" % logs.peek("tb.dut.merger3.axi_rd_4_merger.panic_d_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.panic_c_ids_fifo" % logs.peek("tb.dut.merger3.axi_rd_4_merger.panic_c_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.panic_b_ids_fifo" % logs.peek("tb.dut.merger3.axi_rd_4_merger.panic_b_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.panic_a_ids_fifo" % logs.peek("tb.dut.merger3.axi_rd_4_merger.panic_a_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.a_ar_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_rd_4_merger.a_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.a_ar_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_rd_4_merger.a_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.b_ar_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_rd_4_merger.b_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.b_ar_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_rd_4_merger.b_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.c_ar_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_rd_4_merger.c_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.c_ar_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_rd_4_merger.c_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.d_ar_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_rd_4_merger.d_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.d_ar_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_rd_4_merger.d_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.rdata_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_rd_4_merger.rdata_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_rd_4_merger.rdata_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_rd_4_merger.rdata_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.panic_acount" % logs.peek("tb.dut.merger3.axi_wr_4_merger.panic_acount"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.panic_bcount" % logs.peek("tb.dut.merger3.axi_wr_4_merger.panic_bcount"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.panic_ccount" % logs.peek("tb.dut.merger3.axi_wr_4_merger.panic_ccount"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.panic_dcount" % logs.peek("tb.dut.merger3.axi_wr_4_merger.panic_dcount"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.panic_rw_fifo" % logs.peek("tb.dut.merger3.axi_wr_4_merger.panic_rw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.panic_d_aw_fifo" % logs.peek("tb.dut.merger3.axi_wr_4_merger.panic_d_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.panic_c_aw_fifo" % logs.peek("tb.dut.merger3.axi_wr_4_merger.panic_c_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.panic_b_out_fifo" % logs.peek("tb.dut.merger3.axi_wr_4_merger.panic_b_out_fifo"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.panic_b_aw_fifo" % logs.peek("tb.dut.merger3.axi_wr_4_merger.panic_b_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.panic_aw_fifo" % logs.peek("tb.dut.merger3.axi_wr_4_merger.panic_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.panic_a_aw_fifo" % logs.peek("tb.dut.merger3.axi_wr_4_merger.panic_a_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.a_aw_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_wr_4_merger.a_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.a_aw_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_wr_4_merger.a_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.a_win_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_wr_4_merger.a_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.a_win_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_wr_4_merger.a_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.aw_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_wr_4_merger.aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.aw_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_wr_4_merger.aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.b_aw_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_wr_4_merger.b_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.b_aw_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_wr_4_merger.b_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.b_win_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_wr_4_merger.b_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.b_win_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_wr_4_merger.b_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.c_aw_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_wr_4_merger.c_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.c_aw_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_wr_4_merger.c_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.c_win_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_wr_4_merger.c_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.c_win_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_wr_4_merger.c_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.d_aw_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_wr_4_merger.d_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.d_aw_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_wr_4_merger.d_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.d_win_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_wr_4_merger.d_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.d_win_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_wr_4_merger.d_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.rw_fifo.panic_in" % logs.peek("tb.dut.merger3.axi_wr_4_merger.rw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger3.axi_wr_4_merger.rw_fifo.panic_out" % logs.peek("tb.dut.merger3.axi_wr_4_merger.rw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.panic_d_ids_fifo" % logs.peek("tb.dut.merger4.axi_rd_4_merger.panic_d_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.panic_c_ids_fifo" % logs.peek("tb.dut.merger4.axi_rd_4_merger.panic_c_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.panic_b_ids_fifo" % logs.peek("tb.dut.merger4.axi_rd_4_merger.panic_b_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.panic_a_ids_fifo" % logs.peek("tb.dut.merger4.axi_rd_4_merger.panic_a_ids_fifo"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.a_ar_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_rd_4_merger.a_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.a_ar_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_rd_4_merger.a_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.b_ar_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_rd_4_merger.b_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.b_ar_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_rd_4_merger.b_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.c_ar_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_rd_4_merger.c_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.c_ar_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_rd_4_merger.c_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.d_ar_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_rd_4_merger.d_ar_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.d_ar_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_rd_4_merger.d_ar_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.rdata_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_rd_4_merger.rdata_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_rd_4_merger.rdata_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_rd_4_merger.rdata_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.panic_acount" % logs.peek("tb.dut.merger4.axi_wr_4_merger.panic_acount"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.panic_bcount" % logs.peek("tb.dut.merger4.axi_wr_4_merger.panic_bcount"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.panic_ccount" % logs.peek("tb.dut.merger4.axi_wr_4_merger.panic_ccount"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.panic_dcount" % logs.peek("tb.dut.merger4.axi_wr_4_merger.panic_dcount"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.panic_rw_fifo" % logs.peek("tb.dut.merger4.axi_wr_4_merger.panic_rw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.panic_d_aw_fifo" % logs.peek("tb.dut.merger4.axi_wr_4_merger.panic_d_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.panic_c_aw_fifo" % logs.peek("tb.dut.merger4.axi_wr_4_merger.panic_c_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.panic_b_out_fifo" % logs.peek("tb.dut.merger4.axi_wr_4_merger.panic_b_out_fifo"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.panic_b_aw_fifo" % logs.peek("tb.dut.merger4.axi_wr_4_merger.panic_b_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.panic_aw_fifo" % logs.peek("tb.dut.merger4.axi_wr_4_merger.panic_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.panic_a_aw_fifo" % logs.peek("tb.dut.merger4.axi_wr_4_merger.panic_a_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.a_aw_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_wr_4_merger.a_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.a_aw_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_wr_4_merger.a_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.a_win_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_wr_4_merger.a_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.a_win_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_wr_4_merger.a_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.aw_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_wr_4_merger.aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.aw_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_wr_4_merger.aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.b_aw_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_wr_4_merger.b_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.b_aw_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_wr_4_merger.b_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.b_win_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_wr_4_merger.b_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.b_win_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_wr_4_merger.b_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.c_aw_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_wr_4_merger.c_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.c_aw_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_wr_4_merger.c_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.c_win_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_wr_4_merger.c_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.c_win_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_wr_4_merger.c_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.d_aw_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_wr_4_merger.d_aw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.d_aw_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_wr_4_merger.d_aw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.d_win_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_wr_4_merger.d_win_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.d_win_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_wr_4_merger.d_win_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.rw_fifo.panic_in" % logs.peek("tb.dut.merger4.axi_wr_4_merger.rw_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.merger4.axi_wr_4_merger.rw_fifo.panic_out" % logs.peek("tb.dut.merger4.axi_wr_4_merger.rw_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.panic_r_fifo" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.panic_r_fifo"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.panic_ar_fifo" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.panic_ar_fifo"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.panic_in" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.panic_out" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.a_r_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.panic_in" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.panic_out" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.b_r_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.back_r_fifo.panic_in" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.back_r_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.back_r_fifo.panic_out" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.back_r_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.panic_in" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.panic_out" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.c_r_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.panic_in" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.panic_out" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.d_r_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.r_fifo.panic_in" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.r_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_rd_4_splitter.r_fifo.panic_out" % logs.peek("tb.dut.splitter0.axi_rd_4_splitter.r_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.panic_w_fifo" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.panic_w_fifo"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.panic_order_fifo" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.panic_order_fifo"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.panic_b_fifo" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.panic_b_fifo"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.panic_aw_fifo" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.panic_aw_fifo"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.panic_in" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.panic_out" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_a_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.panic_in" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.panic_out" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_b_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.panic_in" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.panic_out" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_c_fifo.panic_out"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.panic_in" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.panic_in"))
    logs.log_info("SNP %x  tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.panic_out" % logs.peek("tb.dut.splitter0.axi_wr_4_splitter.back_bid_d_fifo.panic_out"))
