#! /bin/csh -f
set TEST = test0
set TEST = test2
/bin/rm tb.vvp
comp
~/verification_libs3/scanDeepListForPanics.py 
~/verification_libs3/scanDeepListForPanics.py deep.list count

simv $TEST.seq +LOG=$TEST




