#! /bin/csh -f

#SKELETON of modelsim

#     
#         hello.c:
#             #include "veriuser.h"
#             static PLI_INT32 hello()
#             {
#               io_printf("Hi there\n");
#     return 0; }
#             s_tfcell veriusertfs[] = {
#               {usertask, 0, 0, 0, hello, 0, "$hello"},
#               {0}  /* last entry must be 0 */
#     }; 
#     
#     hello.v:
#             module hello;
#               initial $hello;
#             endmodule
#     

#    Compile the PLI code for a 32-bit Linux Platform:

gcc -c -I <install_dir>/questasim/include hello.c
gcc -shared -Bsymbolic -o hello.so hello.o -lc


#    Compile the Verilog code:
vlib work
vlog hello.v
#    Simulate the design:
vsim -c -pli hello.so hello

